version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install awscli --upgrade --user
      - pip install -r requirements.txt

#  pre_build:

  build:
    commands:
      - python -m pytest --junitxml=$CODEBUILD_SRC_DIR/test-reports/test-report.xml

reports:
  pytest_reports:
    files:
      - test-report.xml
    base-directory: $CODEBUILD_SRC_DIR/test-reports
    file-format: JUNITXML
