version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip3 install awscli --upgrade --user
      - pip install -r requirements.txt
  build:
    commands:
      - pytest
