AWSTemplateFormatVersion: '2010-09-09'

Description: Packer test instance.

Parameters: 

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID.

  SubnetId:
    Type: String
    Description: Subnet ID placement

  AZ:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Availability Zone placement

  SecurityGroup:
    Description: Security group ID
    Type: String

  KeyPair:
    Description: Key Pair Name
    Type: AWS::EC2::KeyPair::KeyName

  InstanceProfile:
    Description: EC2 Instance Profile
    Type: String

  LatestUbuntuFocalAMI:
    Description: Ubuntu AMI
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/focal/stable/current/amd64/hvm/ebs-gp2/ami-id

Resources:

  PackerInstance:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
      - !Ref SecurityGroup
      KeyName: !Ref KeyPair
      InstanceType: r5.large # r5.2xlarge # TODO season to taste
      AvailabilityZone: !Ref AZ
      ImageId: !Ref LatestUbuntuFocalAMI
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp3
            VolumeSize: '200' # '1000'  # TODO season to taste
      Tags:
        - Key: Name
          Value: packer-test
      IamInstanceProfile: !Ref InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "## Installing Dependencies..."
          apt update
          apt install git openssl rsync make -y
          apt install software-properties-common -y
          add-apt-repository ppa:deadsnakes/ppa -y
          apt install python3.10 -y   # latest ubuntu on AWS has only Python 3.8.10
          rm /usr/bin/python3 # remove symlink to preinstalled python3.8
          ln -sf /usr/bin/python3.10 /usr/bin/python3
          ln -sf /usr/bin/python3 /usr/bin/python

          apt install -y python3.10-distutils
          apt install -y python3-apt
          ## Fixes: https://stackoverflow.com/questions/13708180/python-dev-installation-error-importerror-no-module-named-apt-pkg
          cd /usr/lib/python3/dist-packages
          ln -s apt_pkg.cpython-38-x86_64-linux-gnu.so apt_pkg.so

          curl https://bootstrap.pypa.io/get-pip.py | python3
          /usr/local/bin/pip  install -r requirements.txt

          curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
          sudo apt -y install nodejs
          npm install -g ipfs-car
          cd /root
          git clone https://github.com/frank-ang/packer.git
          cd /root/packer
          git fetch
          git switch test  # testing on "test" branchname
          pip install -r requirements.txt

Outputs:
  InstanceId:
    Description: InstanceId of the packer EC2 instance
    Value:
      Ref: PackerInstance
  PublicIP:
    Description: Public IP address of the packer EC2 instance
    Value:
      Fn::GetAtt:
      - PackerInstance
      - PublicIp
