version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.1
workflows:
  build_and_test:
    jobs:
      - tests:
          filters:
            branches:
              only: 
                - master
                - test

executors:
  my-executor:
    docker:
      - image: cimg/python:3.10.4-node
    ## 2xlarge resource not available on CircleCI free plan.
    ## https://circleci.com/docs/2.0/configuration-reference/#docker
    # resource_class: 2xlarge+ # not available on free plan.

jobs:
  tests:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Dump environment
          command: |
            printenv
            pwd
            df -h
            mount
            lsblk
            cat /proc/meminfo
      - run:
          name: Install dependencies 
          command: |
            set -e
            echo "## Installing Dependencies..."
            sudo apt-get update -y
            sudo apt-get install -y rsync unzip
            sudo npm install -g ipfs-car
            pip install -r requirements.txt
            # sudo apt install golang-go
            wget -c https://go.dev/dl/go1.18.3.linux-amd64.tar.gz
            sudo tar -C /usr/local/ -xzf go1.18.3.linux-amd64.tar.gz
            echo 'export GOPATH=/home/circleci/go' >> $BASH_ENV
            echo 'export GOBIN=$GOPATH/bin' >> $BASH_ENV
            echo 'export GOROOT=/usr/local/go' >> $BASH_ENV
            echo 'export GOCACHE=off' >> $BASH_ENV
            echo 'export PATH=$PATH:$GOPATH/bin:$GOROOT/bin' >> $BASH_ENV

            source $BASH_ENV
            go version
            go env
            #go get github.com/filecoin-project/go-fil-commp-hashhash/cmd/stream-commp@latest
            #which stream-commp
            #curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            #sudo unzip awscliv2.zip
            #sudo ./aws/install
      - run:
          name: Verify Golang and install stream-commp
          command: |
            set -e
            source $BASH_ENV
            go version
            go env
            go install github.com/filecoin-project/go-fil-commp-hashhash/cmd/stream-commp@latest
            echo "installed stream-commp..."
            find /home/circleci/
            echo gobin: $GOBIN , goroot: $GOROOT
            find $GOBIN
            find $GOROOT
            fubar
            which stream-commp
            barfu

      - run:
          name: Initialize tests, generate key pair.
          command: |
            make init_testdata
      - run:
          name: Test small and medium data
          command: |
            set -e
            echo "## Running regular tests..."
            make test_all
            python -m pytest test/test_packer.py -o log_cli=true -o log_cli_level=INFO --junitxml=reports/test-report.xml
      - run:
          name: Test large data
          command: |
            set -e
            echo "## Running large test..."
            make init_largedata
            make test_large
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/test-report.xml
          destination: pytest-report.xml
      - store_artifacts:
          path: reports/
