version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.1
workflows:
  build_and_test:
    jobs:
      - tests:
          filters:
            branches:
              only: 
                - master
                - test

executors:
  my-executor:
    docker:
      - image: cimg/python:3.10.4-node
    ## larger resource, because decryption is memory-intensive. 
    ## 2xlarge: 2 vCPU, 40GB RAM https://circleci.com/docs/2.0/configuration-reference/#docker
    ## Appears to be a CircleCI paid feature.
    resource_class: 2xlarge+

jobs:
  tests:
    #docker:
    #  - image: cimg/python:3.10.4-node
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Dump environment
          command: |
            printenv
            pwd
            df -h
            mount
            lsblk
            cat /proc/meminfo
      - run:
          name: Install dependencies 
          command: |
            echo "## Installing Dependencies..."
            sudo apt-get update -y
            sudo apt-get install -y rsync
            sudo npm install -g ipfs-car
            pip install -r requirements.txt
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"\
            unzip awscliv2.zip
            ./aws/install
      - run:
          name: Initialize tests, generate key pair.
          command: |
            make init_testdata
      - run:
          name: Test small and medium data
          command: |
            echo "## Running regular tests..."
            make test_all
            python -m pytest test/test_packer.py -o log_cli=true -o log_cli_level=INFO --junitxml=reports/test-report.xml
      - run:
          name: Test large data
          command: |
            echo "## Running large test..."
            make init_largedata
            make test_large
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/test-report.xml
          destination: pytest-report.xml
      - store_artifacts:
          path: reports/
