version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.1
workflows:
  build_and_test:
    jobs:
      - tests:
          filters:
            branches:
              only: 
                - master
                - test

executors:
  my-executor:
    docker:
      - image: cimg/python:3.10.4-node
    ## 2xlarge resource not available on CircleCI free plan.
    ## https://circleci.com/docs/2.0/configuration-reference/#docker
    # resource_class: 2xlarge+ # not available on free plan.

jobs:
  tests:
    executor: my-executor
    environment:
    #  - HOME=/root # /home/circleci
      - GOPATH=$HOME/go
      - PATH=/usr/local/go/bin:$GOPATH/bin:$PATH
    steps:
      - checkout
      - run:
          name: Dump environment
          command: |
            printenv
            pwd
            df -h
            mount
            lsblk
            cat /proc/meminfo
      - run:
          name: Install dependencies 
          command: |
            echo "## Installing Dependencies..."
            sudo apt-get update -y
            sudo apt-get install -y rsync unzip
            sudo npm install -g ipfs-car
            pip install -r requirements.txt
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            sudo unzip awscliv2.zip
            sudo ./aws/install
            sudo apt install golang-go
            go version
            go install github.com/filecoin-project/go-fil-commp-hashhash/cmd/stream-commp@latest

      - run:
          name: Initialize tests, generate key pair.
          command: |
            make init_testdata
      - run:
          name: Test small and medium data
          command: |
            echo "## Running regular tests..."
            make test_all
            python -m pytest test/test_packer.py -o log_cli=true -o log_cli_level=INFO --junitxml=reports/test-report.xml
      - run:
          name: Test large data
          command: |
            echo "## Running large test..."
            make init_largedata
            make test_large
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/test-report.xml
          destination: pytest-report.xml
      - store_artifacts:
          path: reports/
