version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.1
workflows:
  build_and_test:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/python:3.10.4-node
    # larger resource, because decryption is memory-intensive. 
    # 2xlarge: 2 vCPU, 40GB RAM https://circleci.com/docs/2.0/configuration-reference/#docker
    resource_class: 2xlarge+
    steps:
      - checkout
      - run:
          name: Dump environment
          command: |
            printenv
            pwd
            df -h
            mount
            lsblk
            cat /proc/meminfo
      - run:
          name: Install dependencies 
          command: |
            echo "## Installing Dependencies..."
            sudo apt-get update -y
            sudo apt-get install -y rsync
            sudo npm install -g ipfs-car
            pip install -r requirements.txt
      - run:
          name: Init Test Data
          command: |
            make init_testdata
      - run:
          name: Run tests
          command: |
            echo "## Running regular tests..."
            make test_all
            python -m pytest test/test_packer.py -o log_cli=true -o log_cli_level=INFO --junitxml=reports/test-report.xml
      - run:
          name: Run large test
          command: |
            echo "## Running large test..."
            make init_largedata
            make test_large
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/test-report.xml
          destination: pytest-report.xml
      - store_artifacts:
          path: reports/
