version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.1
  rsync: aplazame/rsync@0.0.17
workflows:
  test: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/python:3.10.4-node
    steps:
      - checkout
#      - python/install-packages:    ## CI error ... test'Cannot find orb 'python' looking for command named 'python/install-packages'
#          pkg-manager: pip
      - run:
          name: Install dependencies 
          command: |
            pip install -r requirements.txt
            python --version
            node --version
            npm --version
            echo "installing ipfs-car..."
            sudo npm install -g ipfs-car
      - run: echo "Testing Packer..."
      - run:
          name: Run tests
          command: |
            make init_testdata
            make test_all
            make test_large
            python -m pytest test/test_packer.py --junitxml=reports/test-report.xml
      - store_test_results:
          path: reports/
#      - persist_to_workspace:
#          root: ~/project
#          paths:
#            - .